version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8000"
    environment:
      - PORT=8000
      - LOG_PATH=/app/log/app.log
    labels:
      logging: "promtail"
      logging_jobname: "webapp_logs"
    volumes:
      - log-data:/app/log
  grafana:
    image: grafana/grafana
    ports:
      - "9090:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./loki-config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    image: grafana/promtail
    volumes:
      - ./loki-config/promtail.yaml:/etc/promtail/webapp-config.yaml
      - log-data:/var/log/webapp
    command: -config.file=/etc/promtail/webapp-config.yaml
    depends_on:
      - loki
volumes:
  log-data: